src/Entity/Show.php
<?php

namespace App\Entity;

use App\Repository\ShowRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator as AcmeAssert;

#[ORM\Entity(repositoryClass: ShowRepository::class)]
#[ORM\Table(name: '`show`')]
class Show
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\LessThan(
        propertyPath: 'date_end',
        message: 'La date de début doit être antérieur à la date de fin'

    )]
    #[AcmeAssert\CreneauHoraire]
    private ?\DateTimeInterface $date_start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThan(
        propertyPath: 'date_start',
        message: 'La date de fin doit être postérieure à la date de début'

    )]
    private ?\DateTimeInterface $date_end = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'shows')]
    private Collection $categories;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image]
    private ?string $affiche = null;

    #[ORM\OneToMany(mappedBy: 'spectacle', targetEntity: Reservation::class)]
    private Collection $reservations;

    public function __construct()
    {
        $this->categories = new ArrayCollection();

        $this->date_start = new DateTime('now');
        $this->date_end = new DateTime('now +1hours');
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(?string $affiche): self
    {
        $this->affiche = $affiche;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setSpectacle($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getSpectacle() === $this) {
                $reservation->setSpectacle(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->id;
    }
}

src/Form/ShowType.php
<?php

namespace App\Form;

use App\Entity\Show;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                'label' => "Nom de l'événement"
            ])
            ->add('description', null, [
                'label' => "Description"
            ])
            ->add('date_start', null, [
                'label' => 'Date de début',
                'widget' => 'single_text',
                'attr' => ['step' => '1']
            ])
            ->add('date_end', null, [
                'label' => 'Date de fin',
                'widget' => 'single_text',
                'attr' => ['step' => '1']
            ])
            ->add('categories', null, [
                'label' => 'Catégories'
            ])
            ->add('affiche', FileType::class, [
                'label' => "Affiche (jpg, jpeg, png)",
                'data_class' => null
            ])
            ->add('ok', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Show::class,
        ]);
    }
}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use App\Entity\Configuration;
use App\Entity\Show;
use App\Form\ShowType;
use App\Repository\SeatRepository;
use App\Repository\ShowRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/show')]
class ShowController extends AbstractController
{
    #[Route('/', name: 'app_show_index', methods: ['GET'])]
    public function index(ShowRepository $showRepository, EntityManagerInterface $entityManager, SeatRepository $seatRepository): Response
    {
        $configuration = $entityManager->find(Configuration::class, 1);

        $shows = $showRepository->findRecentShow();

        $nb_places = $seatRepository->getNbPlaces();

        return $this->render('show/index.html.twig', [
            'shows' => $shows,
            'configuration' => $configuration,
            'nb_places' => $nb_places
        ]);
    }

    #[Route('/map', name: 'app_show_map', methods: ['GET'])]
    public function map(EntityManagerInterface $entityManager)
    {
        $configuration = $entityManager->find(Configuration::class, 1);
        return $this->render('show/map.html.twig', [
            'configuration' => $configuration
        ]);
    }

    #[Route('/new', name: 'app_show_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ShowRepository $showRepository, EntityManagerInterface $entityManager): Response
    {
        $configuration = $entityManager->find(Configuration::class, 1);

        $show = new Show();
        $form = $this->createForm(ShowType::class, $show);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $affiche = $form->get('affiche')->getData();

            if ($affiche) {

                $affiche_nom = uniqid() . '.' . $affiche->guessExtension();

                $affiche->move(
                    $this->getParameter('affiches_directory'),
                    $affiche_nom
                );

                $show->setAffiche($affiche_nom);
            }

            $showRepository->save($show, true);

            return $this->redirectToRoute('app_show_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('show/new.html.twig', [
            'show' => $show,
            'form' => $form,
            'configuration' => $configuration
        ]);
    }

    #[Route('/edit/{id}', name: 'app_show_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Show $show, ShowRepository $showRepository, EntityManagerInterface $entityManager): Response
    {
        $configuration = $entityManager->find(Configuration::class, 1);

        $form = $this->createForm(ShowType::class, $show);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $affiche = $form->get('affiche')->getData();

            if ($affiche) {

                $affiche_nom = uniqid() . '.' . $affiche->guessExtension();

                $affiche->move(
                    $this->getParameter('affiches_directory'),
                    $affiche_nom
                );

                $show->setAffiche($affiche_nom);
            }

            $showRepository->save($show, true);

            return $this->redirectToRoute('app_show_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('show/edit.html.twig', [
            'show' => $show,
            'form' => $form,
            'configuration' => $configuration
        ]);
    }

    #[Route('/delete/{id}', name: 'app_show_delete', methods: ['POST'])]
    public function delete(Request $request, Show $show, ShowRepository $showRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$show->getId(), $request->request->get('_token'))) {
            $showRepository->remove($show, true);
        }

        return $this->redirectToRoute('app_show_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/show/_delete_form.html.twig
<form method="post" action="{{ path('app_show_delete', {'id': show.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ show.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/show/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/show/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Édition d'un spectacle</h2>

    {{ include('show/_form.html.twig', {'button_label': 'Update'}) }}

    <hr/>

    {{ include('show/_delete_form.html.twig') }}
{% endblock %}

templates/show/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h2>Spectacles</h2>

	<div class="row">
		{% for show in shows %}
			<div class="col-sm-4 p-2">
				<div class="card">
					{% if show.affiche is not null %}
					<img src="/uploads/affiches/{{ show.affiche }}" alt="{{ show.name }}" class="card-img-top">
					{% endif %}
					<div class="card-header">
						<span class="badge text-bg-info float-end">
							<big>{{ show.dateStart ? show.dateStart|date('d') : '' }}</big>
							<br/>
							{{ show.dateStart ? show.dateStart|date('M') : '' }}<br/>
							{{ show.dateStart ? show.dateStart|date('Y') : '' }}
						</span>

						<h4 class="card-title">{{ show.name }}</h4>

						{% set categories =  [] %}
						{% for categorie in  show.categories %}
							{% set categories = categories|merge([categorie.name]) %}
						{% endfor %}
						<i>{{ categories|join('<span class="text-secondary mx-1">//</span>')|raw }}</i>
					</div>
					<div class="card-body">
						<p>
							{{ show.description }}
						</p>
						<span>Places restantes : {{ nb_places - show.reservations|length}}</span>
					</div>
					<div class="card-footer">
						<td>
                            <a class="btn btn-primary float-start" href="{{ path('app_show_map') }}">plan</a>
							{% if is_granted('ROLE_ADMIN') %}
							<a class="btn btn-primary float-end" href="{{ path('app_show_edit', {'id': show.id}) }}">éditer</a>
							{% endif %}
							{% if is_granted('ROLE_USER') %}
								<a class="btn btn-primary float-end" href="{{ path('app_reservation', {'id': show.id}) }}">réserver</a>
							{% endif %}
						</td>
					</div>
				</div>
			</div>
		{% else %}
			<div class="alert alert-warning">Aucun spectacle!</div>
		{% endfor %}
	</div>

	<hr/>

	{% if is_granted('ROLE_ADMIN') %}
	<a class="btn btn-success" href="{{ path('app_show_new') }}">Ajouter</a>
	{% endif %}

{% endblock %}

templates/show/map.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h2>Plan des places</h2>

    <div class="alert alert-info">
        Sur ce plan, il est possible de consulter l'occupation des places pour ce spectacle!
        Les cases occupées sont affichées en opacité réduite.
    </div>

    <table class="table table-striped">
        <tr>
            <td colspan="8" class="text-center">
                <h4>Scène</h4>
            </td>
        </tr>
        <tr>
            <td class="opacity-25">A1</td>
            <td class="opacity-25">A2</td>
            <td class="opacity-25">A3</td>
            <td class="opacity-25">A4</td>
            <td class="opacity-25">A5</td>
            <td class="opacity-25">A6</td>
            <td class="opacity-25">A7</td>
            <td class="opacity-25">A8</td>
        </tr>
        <tr>
            <td>B1</td>
            <td>B2</td>
            <td class="opacity-25">B3</td>
            <td>B4</td>
            <td class="opacity-25">B5</td>
            <td class="opacity-25">B6</td>
            <td>B7</td>
            <td>B8</td>
        </tr>
        <tr>
            <td>C1</td>
            <td>C2</td>
            <td>C3</td>
            <td>C4</td>
            <td>C5</td>
            <td>C6</td>
            <td>C7</td>
            <td>C8</td>
        </tr>
        <tr>
            <td>D1</td>
            <td>D2</td>
            <td>D3</td>
            <td>D4</td>
            <td>D5</td>
            <td>D6</td>
            <td>D7</td>
            <td>D8</td>
        </tr>
        <tr>
            <td>E1</td>
            <td>E2</td>
            <td>E3</td>
            <td>E4</td>
            <td>E5</td>
            <td>E6</td>
            <td>E7</td>
            <td>E8</td>
        </tr>
    </table>
{% endblock %}

templates/show/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Ajout d'un spectacle</h2>

    {{ include('show/_form.html.twig') }}
{% endblock %}